resolveRpgSynonyms <- function(x) UseMethod("resolveRpgSynonyms", x)

resolveRpgSynonyms.PlainTextDocument <- resolveRpgSynonyms.character <- function(x){
  
  i.c <- TRUE
  
  # separatori comuni
  x <- gsub("/", " ", x, ignore.case = i.c)
  x <- gsub("@", " ", x, ignore.case = i.c)
  x <- gsub("-", " ", x, ignore.case = i.c)
  
  # italian tanslations
  x <- gsub("cani nella vigna", "dogs in the vineyard", x, ignore.case = i.c)
  x <- gsub("anime & sangue", "anime e sangue", x, ignore.case = i.c)
  x <- gsub("project h.o.p.e.", "project hope", x, ignore.case = i.c)
  x <- gsub("cano nella vigna", "dogs in the vineyard", x, ignore.case = i.c)
  x <- gsub("avventure in prima serata", "primetime adventures", x, ignore.case = i.c)
  x <- gsub("cano nella vigna", "dogs in the vineyard", x, ignore.case = i.c)
  x <- gsub("richiamo di", "call of", x, ignore.case = i.c)
  x <- gsub("tracce di", "trail of", x, ignore.case = i.c)
  x <- gsub("martelli da guerra", "warhammer", x, ignore.case = i.c)
  x <- gsub("mdg", "warhammer", x, ignore.case = i.c)
  x <- gsub("mondo di tenebra", "world of darkness", x, ignore.case = i.c)
  x <- gsub("mdt", "world of darkness", x, ignore.case = i.c)
  x <- gsub("nmdt", "world of darkness", x, ignore.case = i.c)
  x <- gsub("licantropi", "werewolf", x, ignore.case = i.c)
  x <- gsub("vampire", "vampiri", x, ignore.case = i.c)
  x <- gsub("non cedere al sonno", "don't rest your head", x, ignore.case = i.c)
  x <- gsub("guerre stellari", "star wars", x, ignore.case = i.c)
  x <- gsub("unico anello", "one ring", x, ignore.case = i.c)
  x <- gsub("l5a", "legend of the five rings", x, ignore.case = i.c)
  x <- gsub("leggenda dei 5 anelli", "legends of the five rings", x, ignore.case = i.c)
  x <- gsub("leggenda dei cinque anelli", "legends of the five rings", x, ignore.case = i.c)
  x <- gsub("gusto del delitto", "taste for murder", x, ignore.case = i.c)
  x <- gsub("mia vita col padrone", "my life with master", x, ignore.case = i.c)
  x <- gsub("solipsisti", "solipsists", x, ignore.case = i.c)
  x <- gsub("esoterroristi", "esoterrorists", x, ignore.case = i.c)
  x <- gsub("buffy l'ammazzavampiri", "buffy", x, ignore.case = i.c)
  x <- gsub("richiamo di", "call of", x, ignore.case = i.c)
  x <- gsub("cuori di mostro", "monsterhearts", x, ignore.case = i.c)
  x <- gsub("penny per i miei pensieri", "a penny for my thoughts", x, ignore.case = i.c)
  x <- gsub("di cosa hai paura", "fear itself", x, ignore.case = i.c)
  x <- gsub("sporchi segreti", "dirty secrets", x, ignore.case = i.c)
  x <- gsub("spirito del secolo", "spirit of the century", x, ignore.case = i.c)
  x <- gsub("trono di spade", "a game of throne", x, ignore.case = i.c)
  x <- gsub("tredicesima era", "13th age", x, ignore.case = i.c)
  
  # sinonimi
  x <- gsub("buffy the vampire slayer", "buffy", x, ignore.case = i.c)
  x <- gsub("advanced dungeons & dragons", "ad&d", x, ignore.case = i.c)
  x <- gsub("adnd", "ad&d", x, ignore.case = i.c)
  x <- gsub("advanced dungeons and dragons", "ad&d", x, ignore.case = i.c)
  x <- gsub("dungeons & dragons", "d&d", x, ignore.case = i.c)
  x <- gsub("dnd", "d&d", x, ignore.case = i.c)
  x <- gsub("dungeons and dragons", "d&d", x, ignore.case = i.c)
  x <- gsub("project hope", "project h.o.p.e.", x, ignore.case = i.c)
  x <- gsub("cyberpunk", "cyberpunk 2020", x, ignore.case = i.c)
  x <- gsub("warhammer 40000", "dark heresy", x, ignore.case = i.c)
  x <- gsub("warhammer 40k", "dark heresy", x, ignore.case = i.c)
  x <- gsub("wfb", "warhmmer", x, ignore.case = i.c)
  x <- gsub("wfrp", "warhammer", x, ignore.case = i.c)
  x <- gsub("3.16", "3:16", x, ignore.case = i.c)
  x <- gsub("coc", "call of cthulhu", x, ignore.case = i.c)
  x <- gsub("cthulu", "call of cthulhu", x, ignore.case = i.c)
  x <- gsub("trails of cthulhu", "trail of cthulhu", x, ignore.case = i.c)
  x <- gsub("l5r", "legend of the five rings", x, ignore.case = i.c)
  x <- gsub("legend of the 5 rings", "legend of the five rings", x, ignore.case = i.c)
  x <- gsub("blood and smoke", "blood & smoke", x, ignore.case = i.c)
  x <- gsub("psirun", "psi*run", x, ignore.case = i.c)
  x <- gsub("twentyone guns", "21 guns", x, ignore.case = i.c)
  x <- gsub("21 gun", "21 guns", x, ignore.case = i.c)
  x <- gsub("twentyone gun", "21 guns", x, ignore.case = i.c)
  x <- gsub("mutants and masterminds", "mutants & masterminds", x, ignore.case = i.c)
  x <- gsub("mutants & mastermind", "mutants & masterminds", x, ignore.case = i.c)
  x <- gsub("mutant & masterminds", "mutants & masterminds", x, ignore.case = i.c)
  x <- gsub("mutant & mastermind", "mutants & masterminds", x, ignore.case = i.c)
  x <- gsub("m&m", "mutants & masterminds", x, ignore.case = i.c)
  x <- gsub("bunnies and burrows", "bunnies & burrows", x, ignore.case = i.c)
  x <- gsub("harnmaster", "hârnmaster", x, ignore.case = i.c)
  x <- gsub("tunnels and trolls", "tunnels & trolls", x, ignore.case = i.c)
  x <- gsub("sw", "star wars", x, ignore.case = i.c)
  x <- gsub("nwod", "world of darkness", x, ignore.case = i.c)
  x <- gsub("owod", "world of darkness", x, ignore.case = i.c)
  x <- gsub("wod", "world of darkness", x, ignore.case = i.c)
  x <- gsub("tmnt", "teenage mutants ninja turtles", x, ignore.case = i.c)
  x <- gsub("tng", "star trek: the next generation", x, ignore.case = i.c)
  x <- gsub("tsc", "mage", x, ignore.case = i.c)
  x <- gsub("besm", "big eyes small mouth", x, ignore.case = i.c)
  x <- gsub("æther", "aeter", x, ignore.case = i.c)
  x <- gsub("megatraveller", "traveller", x, ignore.case = i.c)
  x <- gsub("dogs of war", "dogs of w*a*r", x, ignore.case = i.c)
  x <- gsub("hounds of god", "hounds of g.o.d", x, ignore.case = i.c)
  
  x
}  